config/routes.rb
Rails.application.routes.draw do
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  # get  "sign_up", to: "registrations#new"
  # post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  # resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    # resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  namespace :authentications do
    resources :events, only: :index
  end
  get  "/auth/failure",            to: "sessions/omniauth#failure"
  get  "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "/auth/:provider/callback", to: "sessions/omniauth#create"

  get "templates/:category/:recipe", to: "templates#show", as: :template, defaults: {format: "txt"}

  sitepress_pages
  sitepress_root
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # TODO authenticate the 3 below
  # mount SolidErrors::Engine, at: "/errors"
  # mount Litestream::Engine, at: "/litestream"
  # mount MissionControl::Jobs::Engine, at: "/jobs"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :meta if content_for? :meta %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="canonical" href="https://betterstimulus.com<%= request.path %>" />

    <script defer data-domain="betterstimulus.com" src="https://plausible.io/js/script.js"></script>
    <script type="text/javascript">
     var _iub = _iub || [];
     _iub.csConfiguration = {"siteId":3717385,"cookiePolicyId":34122348,"lang":"en"};
    </script>
    <script type="text/javascript" src="https://cs.iubenda.com/autoblocking/3717385.js"></script>
    <script type="text/javascript" src="//cdn.iubenda.com/cs/tcf/stub-v2.js"></script>
    <script type="text/javascript" src="//cdn.iubenda.com/cs/tcf/safe-tcf-v2.js"></script>
    <script type="text/javascript" src="//cdn.iubenda.com/cs/gpp/stub.js"></script>
    <script type="text/javascript" src="//cdn.iubenda.com/cs/iubenda_cs.js" charset="UTF-8" async></script>
  </head>

  <body>
    <header class="container">
      <nav>
        <ul>
          <li><strong><%= link_to "Better Stimulus JS", "/" %></strong></li>
        </ul>
        <ul>
          <li><%= link_to "Knowledge Base", root_path %></li>
          <li><%= link_to "Cookbook", "#{root_url}cookbook" %></li>
        </ul>
        <ul id="right-nav">
          <li class="search-container">
            <%= render "pagefind/search" %>
          </li>
          <li><%= link_to "Contributors", "/contributors" %></li>
          <li class="sign-in-out-item">
            <% if Current.session.present? %>
              <%= button_to Current.session, method: :delete do %>
                Sign out
                <%= heroicon "arrow-right-on-rectangle" %>
              <% end %>
            <% else %>
              <%= link_to sign_in_path do %>
                Sign in
                <%= heroicon "arrow-left-on-rectangle" %>
              <% end %>
            <% end %>
          </li>
        </ul>
        <!-- mobile nav -->
        <div id="mobile-nav-button">
          <input type="checkbox" id="mobile-nav">
          <label for="mobile-nav" class="hamb"><span class="hamb-line"></span></label>
          <aside>
            <nav>
              <ul>
                <li class="search-container">
                  <%= render "pagefind/search" %>
                </li>
                <li><%= link_to "Contributors", "/contributors" %></li>
                <li class="sign-in-out-item">
                  <% if Current.session.present? %>
                    <%= button_to Current.session, method: :delete do %>
                      Sign out
                      <%= heroicon "arrow-right-on-rectangle" %>
                    <% end %>
                  <% else %>
                    <%= link_to sign_in_path do %>
                      Sign in
                      <%= heroicon "arrow-left-on-rectangle" %>
                    <% end %>
                  <% end %>
                </li>
              </ul>
            </nav>
          </aside>
        </div>
      </nav>
    </header>
    <main class="container">
      <!-- flash row -->
      <% if notice || alert %>
        <div></div>
        <div>
          <% if notice %>
            <section class="label label-green"><%= notice %></section>
          <% end %>
          <% if alert %>
            <section class="label label-red"><%= alert %></section>
          <% end %>
        </div>
        <div></div>
      <% end %>
      
      <!-- breadcrumb row -->
      <div></div>
      <div id="breadcrumbs" data-controller="dialog">
        <dialog data-dialog-target="dialog">
          <article>
            <header>
              <button aria-label="Close" rel="prev" data-action="search#close"></button>
              <p><strong>Articles</strong></p>
            </header>
            <aside>
              <%= content_for :side_nav %>
              <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=<%= Rails.application.credentials.dig(:adsense, :adsense_id) %>"
                      crossorigin="anonymous"></script>
              <!-- betterstimulus-sidebar -->
              <ins class="adsbygoogle"
                   style="display:block"
                   data-ad-client="<%= Rails.application.credentials.dig(:adsense, :adsense_id) %>"
                   data-ad-slot="8143181187"
                   data-ad-format="auto"
                   data-full-width-responsive="true"></ins>
              <script>
               (adsbygoogle = window.adsbygoogle || []).push({});
              </script>
            </aside>
          </article>
        </dialog>
        <%= content_for :breadcrumbs %>
      </div>
      <div></div>
      
      <!-- content row -->
      <aside id="articles-nav">
        <%= content_for :side_nav %>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=<%= Rails.application.credentials.dig(:adsense, :adsense_id) %>"
                crossorigin="anonymous"></script>
        <!-- betterstimulus-sidebar -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="<%= Rails.application.credentials.dig(:adsense, :adsense_id) %>"
             data-ad-slot="8143181187"
             data-ad-format="auto"
             data-full-width-responsive="true"></ins>
        <script>
         (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      </aside>

      <article class="overflow-auto" data-turn-enter data-turn-exit>
        <%= content_for?(:content) ? yield(:content) : yield %>
      </article>

      <aside id="toc">
        <!-- TODO TOC -->
        <!-- <strong>On this page</strong> -->
      </aside>
    </main>
    <footer>
      <div class="grid container">
        <div>
          <div>
            <small><strong>About</strong></small>
            <ul>
              <li><small><%= link_to "Contributors", "/contributors" %></small></li>
              <li><small><%= link_to "Sponsors", "/sponsors" %></small></li>
              <li><small><%= link_to "Imprint", "/imprint" %></small></li>
              <li><a href="https://www.iubenda.com/privacy-policy/34122348" class="iubenda-white iubenda-noiframe iubenda-embed iubenda-noiframe " title="Privacy Policy ">Privacy Policy</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script></li>
              <li><a href="https://www.iubenda.com/privacy-policy/34122348/cookie-policy" class="iubenda-white iubenda-noiframe iubenda-embed iubenda-noiframe " title="Cookie Policy ">Cookie Policy</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script> 
              </li>
              <li><a href="https://www.iubenda.com/terms-and-conditions/34122348" class="iubenda-white iubenda-noiframe iubenda-embed iubenda-noiframe " title="Terms and Conditions ">Terms and Conditions</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script></li>
            </ul>
          </div>
        </div>
        <div>
          <div>
            <small><strong>Open</strong></small>
            <ul>
              <li><small><a href="https://github.com/julianrubisch/better-stimulus" target="_top">GitHub</a></small></li>
              <li><small><a href="https://plausible.io/betterstimulus.com" target="_top">Site Stats</a></small></li> 
            </ul>
          </div>
        </div>
        <div>
          <div>
            <small><strong>Partners</strong></small>
            <ul>
              <li><small><a href="https://hotwire.club" target="_top">The Hotwire Club</a></small></li>
              <li><small><a href="https://www.railsreviews.com" target="_top">RailsReviews</a></small></li> 
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/article.html.erb
<% current_category = KnowledgeBase::Category.find_by(slug: current_page.data.category) %>

<% content_for :title do %>
  <title><%= current_page.data["title"] %> | Betterstimulus</title>
<% end %>

<% if current_page.data["image"].present? %>
  <% content_for :image do %>
    <%= image_url current_page.data["image"]&.split(".")&.insert(-2, "medium")&.join(".") %>
  <% end %>
<% end %>

<% content_for :description do %>
  <meta content="<%= current_page.data["preview_text"] %>" name="description" />
<% end %>

<% content_for :meta do %>
  <% site = Sitepress::Site.new(root_path: "app/content") %>
  <%= display_meta_tags site: "Betterstimulus",
                        title: "#{current_page.data["title"]}",
                        description: current_page.data["preview_text"],
                        icon: '/favicon.ico',
                        reverse: current_page.data["title"] != "Home",
                        og: {
                          title: :title,
                          site_name: :site,
                        },
                        twitter: {
                          card: "summary_large_image",
                          creator: "@julian_rubisch",
                          site: "@julian_rubisch",
                        }
  %>
<% end %>

<% content_for :content do %>
  <% unless current_page.data["title"] == "Home" %>
    <h1><%= current_page.data["title"] %> <% if current_page.data["new"] %><span class="label label-purple">New</span><% end %></h1>
  <% end %>
  <% if current_page.data["author"].present? %>
    <% author = PageModel.find(current_page).author %>
    <h6>by <%= link_to_page author %> <%= image_tag "#{author.github_avatar_url}?size=24" %></h6>
  <% end %>
  <% if current_page.data["authors"].present? %>
    <% authors = PageModel.find(current_page).authors %>
    <h6>by
      <%# TODO to_sentence %>
      <% authors.each do |author| %>
        <%= link_to_page author %> <%= image_tag "#{author.github_avatar_url}?size=24" %>, 
      <% end %>
    </h6>
  <% end %>
  <%= yield %>
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=<%= Rails.application.credentials.dig(:adsense, :adsense_id) %>"
     crossorigin="anonymous"></script>
  <!-- betterstimulus-in-article -->
  <ins class="adsbygoogle"
       style="display:block; text-align:center;"
       data-ad-layout="in-article"
       data-ad-format="fluid"
       data-ad-client="ca-pub-9363950242132313"
       data-ad-slot="7642058661"></ins>
  <script>
   (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
<% end %>

<% content_for :side_nav do %>
  <%= render "nav/articles_nav", current_category: %>
<% end %>

<% content_for :breadcrumbs do %>
  <nav aria-label="breadcrumb">
    <ul>
      <li><button data-action="dialog#open" id="breadcrumb-dialog-button"><%= heroicon "bars-3" %></button></li>
      <% if current_category %>
        <li><a href="#"><%= current_category %></a></li>
      <% end %>
      <li><%= current_page.data.title %></li>
    </ul>
  </nav>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Betterstimulus</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :meta if content_for? :meta %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="canonical" href="https://betterstimulus.com<%= request.path %>" />

    <script defer data-domain="betterstimulus.com" src="https://plausible.io/js/script.js"></script>
    <script type="text/javascript">
     var _iub = _iub || [];
     _iub.csConfiguration = {"siteId":3717385,"cookiePolicyId":34122348,"lang":"en"};
    </script>
    <script type="text/javascript" src="https://cs.iubenda.com/autoblocking/3717385.js"></script>
    <script type="text/javascript" src="//cdn.iubenda.com/cs/tcf/stub-v2.js"></script>
    <script type="text/javascript" src="//cdn.iubenda.com/cs/tcf/safe-tcf-v2.js"></script>
    <script type="text/javascript" src="//cdn.iubenda.com/cs/gpp/stub.js"></script>
    <script type="text/javascript" src="//cdn.iubenda.com/cs/iubenda_cs.js" charset="UTF-8" async></script>
  </head>

  <body>
    <header class="container">
      <nav>
        <ul>
          <li><strong><%= link_to "Better Stimulus JS", "/" %></strong></li>
        </ul>
        <ul>
          <li><%= link_to "Knowledge Base", root_path %></li>
          <li><%= link_to "Cookbook", "#{root_url}cookbook" %></li>
        </ul>
        <ul id="right-nav">
          <li class="search-container">
            <%= render "pagefind/search" %>
          </li>
          <li><%= link_to "Contributors", "/contributors" %></li>
        </ul>
        <!-- mobile nav -->
        <div id="mobile-nav-button">
          <input type="checkbox" id="mobile-nav">
          <label for="mobile-nav" class="hamb"><span class="hamb-line"></span></label>
          <aside>
            <nav>
              <ul>
                <li class="search-container">
                  <%= render "pagefind/search" %>
                </li>
                <li><%= link_to "Contributors", "/contributors" %></li>
              </ul>
            </nav>
          </aside>
        </div>
      </nav>
    </header>
    <main class="container">
      <!-- flash row -->
      <% if notice || alert %>
        <div></div>
        <div>
          <% if notice %>
            <section class="label label-green"><%= notice %></section>
          <% end %>
          <% if alert %>
            <section class="label label-red"><%= alert %></section>
          <% end %>
        </div>
        <div></div>
      <% end %>

      <div></div>
      <div><%= yield %></div>
      <div></div>
    </main>
    <footer>
      <div class="grid container">
        <div>
          <div>
            <small><strong>About</strong></small>
            <ul>
              <li><small><%= link_to "Contributors", "/contributors" %></small></li>
              <li><small><%= link_to "Sponsors", "/sponsors" %></small></li>
              <li><small><%= link_to "Imprint", "/imprint" %></small></li>
              <li><a href="https://www.iubenda.com/privacy-policy/34122348" class="iubenda-white iubenda-noiframe iubenda-embed iubenda-noiframe " title="Privacy Policy ">Privacy Policy</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script></li>
              <li><a href="https://www.iubenda.com/privacy-policy/34122348/cookie-policy" class="iubenda-white iubenda-noiframe iubenda-embed iubenda-noiframe " title="Cookie Policy ">Cookie Policy</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script> 
              </li>
              <li><a href="https://www.iubenda.com/terms-and-conditions/34122348" class="iubenda-white iubenda-noiframe iubenda-embed iubenda-noiframe " title="Terms and Conditions ">Terms and Conditions</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script></li>
            </ul>
          </div>
        </div>
        <div>
          <div>
            <small><strong>Open</strong></small>
            <ul>
              <li><small><a href="https://github.com/julianrubisch/better-stimulus" target="_top">GitHub</a></small></li>
              <li><small><a href="https://plausible.io/betterstimulus.com" target="_top">Site Stats</a></small></li> 
            </ul>
          </div>
        </div>
        <div>
          <div>
            <small><strong>Partners</strong></small>
            <ul>
              <li><small><a href="https://hotwire.club" target="_top">The Hotwire Club</a></small></li>
              <li><small><a href="https://www.railsreviews.com" target="_top">RailsReviews</a></small></li> 
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/cookbook.html.erb
<% current_category = Cookbook::Category.find_by(slug: current_page.data.category) %>

<% content_for :title do %>
  <title><%= current_page.data["title"] %> | Betterstimulus</title>
<% end %>

<% if current_page.data["image"].present? %>
  <% content_for :image do %>
    <%= image_url current_page.data["image"]&.split(".")&.insert(-2, "medium")&.join(".") %>
  <% end %>
<% end %>

<% content_for :description do %>
  <meta content="<%= current_page.data["preview_text"] %>" name="description" />
<% end %>

<% content_for :meta do %>
  <% site = Sitepress::Site.new(root_path: "app/content") %>
  <%= display_meta_tags site: "Betterstimulus",
                        title: "#{current_page.data["title"]}",
                        description: current_page.data["preview_text"],
                        icon: '/favicon.ico',
                        reverse: true,
                        og: {
                          title: :title,
                          site_name: :site,
                        },
                        twitter: {
                          card: "summary_large_image",
                          creator: "@julian_rubisch",
                          site: "@julian_rubisch",
                        }
  %>
<% end %>

<% content_for :content do %>
  <h1><%= current_page.data["title"] %> <% if current_page.data["auth"] %><span class="label label-blue">Pro</span><% end %> <% if current_page.data["new"] %><span class="label label-purple">New</span><% end %></h1>
  <% if current_page.data["author"].present? %>
    <% author = PageModel.find(current_page).author %>
    <h6>by <%= link_to_page author %> <%= image_tag "#{author.github_avatar_url}?size=24" %></h6>
  <% end %>
  <% if current_page.data["authors"].present? %>
    <% authors = PageModel.find(current_page).authors %>
    <h6>by
      <%# TODO to_sentence %>
      <% authors.each do |author| %>
        <%= link_to_page author %> <%= image_tag "#{author.github_avatar_url}?size=24" %>, 
      <% end %>
    </h6>
  <% end %>

  <%# if authenticated, authorize %>
  <% if current_page.data["category"] && RecipePolicy.new(Current.user, current_page).show? %>
    <%= render "cookbook/install_instructions", url: template_url(current_page.data["category"], current_page.request_path.split("/").last)  %>
    <%# TODO also check if authenticated in template controller %>
  <% end %>
  
  <% if current_page.data["stackblitz_url"] && RecipePolicy.new(Current.user, current_page).show? %>
    <%= render "cookbook/code", embed_url: current_page.data["stackblitz_url"] %>
  <% end %>

  <% if !RecipePolicy.new(Current.user, current_page).show? %>
    <section><%= current_page.data["preview_text"] %></section>
  <% else %>
    <%= yield %>
  <% end %>

  <% if !RecipePolicy.new(Current.user, current_page).show? %>
    <section>
      <%= button_to "Unlock this recipe with your Hotwire Club Account", "/auth/patreon", "data-turbo" => false %>
    </section>
  <% end %>

  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=<%= Rails.application.credentials.dig(:adsense, :adsense_id) %>"
     crossorigin="anonymous"></script>
  <!-- betterstimulus-in-article -->
  <ins class="adsbygoogle"
       style="display:block; text-align:center;"
       data-ad-layout="in-article"
       data-ad-format="fluid"
       data-ad-client="ca-pub-9363950242132313"
       data-ad-slot="7642058661"></ins>
  <script>
   (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
<% end %>

<% content_for :side_nav do %>
  <%= render "nav/cookbook_nav", current_category: %>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/person.html.erb
<% content_for :content do %>
  <% person = PersonPage.find("people/#{current_page.data['github']}") %>
  <section class="person-header">
    <h1><%= person.title %> <%= image_tag "#{person.github_avatar_url}?size=512" %></h1>
    <%= link_to person.github_url, target: "_blank" do %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3 .3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5 .3-6.2 2.3zm44.2-1.7c-2.9 .7-4.9 2.6-4.6 4.9 .3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3 .7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3 .3 2.9 2.3 3.9 1.6 1 3.6 .7 4.3-.7 .7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3 .7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3 .7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"/></svg>
    <% end %>

    <% if person.twitter.present? %>
      <%= link_to person.twitter_url, target: "_blank" do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"/></svg>
      <% end %>
    <% end %>
  </section>
  <section>
    <h2>Articles</h2>
    <ul>
      <% PageModel.all.select { _1.data["author"] == current_page.data["github"] }.each do |article| %>
        <li>
          <%= link_to_page article %>
        </li>
      <% end %>
    </ul>
  </section>
  <hr>
  <section>
    <%= yield %>
  </section>
<% end %>

<%= render template: "layouts/application" %>